variables:
    KUBE_VERSION:
        description: kubernetes version
        type: String
        required: true
        default: 1.0.6
    KUBE_PROXY_LOG_FILE:
        required: false
        description: kube proxy log file
        default: /var/log/kube-proxy.log
    KUBE_KUBLET_LOG_FILE:
        required: false
        description: kublet log file
        default: /var/log/kube-kublet.log
    VPC_NAME:
        required: true
        description: the name of the VPC
        default: kube-dev
    VPC_CIDR:
        description: the cloudcoreo defined vpc to add this cluster to
        type: String
        required: true
        default: 10.1.0.0/16
    PRIVATE_SUBNET_NAME:
        default: kube-dev-private-us-west-1
        required: true
        descripiton: the name of the private subnet
        description: the cloudcoreo name of the private vpc subnets. eg private-us-west-2c
        type: String
    PRIVATE_ROUTE_NAME:
        description: the private subnet in which the cluster should be added
        type: String
        required: true
        default: dev-private-route
    DNS_ZONE:
        description: the zone in which the internal elb dns entry should be maintained
        type: String
        required: true
        default: dev.aws.lcloud.com
    KUBE_CLUSTER_AMI:
        description: "the ami to launch for the cluster - default is Amazon Linux AMI 2015.03 (HVM), SSD Volume Type"
        switch: "INSTANCE::region"
        cases:
            us-east-1: ami-1ecae776
            us-west-1: ami-d114f295
            us-west-2: ami-e7527ed7
            eu-west-1: ami-a10897d6
            eu-central-1: ami-a8221fb5
            ap-southeast-1: ami-68d8e93a
            ap-northeast-1: ami-cbf90ecb
            ap-southeast-2: ami-fd9cecc7
            sa-east-1: ami-b52890a8
        type: case
        required: true
        overrides:
          - CLUSTER_AMI
    KUBE_NODE_IP_CIDRS:
        default: 10.2.1.0/24
        description: Node IP CIDR block - NOTE: This MUST be different that the cidr specified for the kubernetes master service cidrs
        required: true
    KUBE_NODE_IP_CIDRS_SUBDIVIDER:
        default: 26
        description: kubernetes service cidrs
        type: number
        required: true
    KUBE_MASTER_NAME:
        default: kube-master
        description: the name of the cluster - this will become your dns record too
        type: String
        required: true
    KUBE_NODE_NAME:
        default: kube-node
        description: the name of the cluster - this will become your dns record too
        type: String
        required: true
        overrides:
          - CLUSTER_NAME
    KUBE_NODE_ELB_TRAFFIC_PORTS:
        default:
        description: leave this blank - we are using ELB for health checks only
        type: Array
        required: false
        overrides:
          - CLUSTER_ELB_TRAFFIC_PORTS
    KUBE_NODE_ELB_TRAFFIC_CIDRS:
        default: 
        description: leave this blank - we are using ELB for health checks only
        type: Array
        required: false
        overrides:
          - CLUSTER_ELB_TRAFFIC_CIDRS
    KUBE_NODE_TCP_HEALTH_CHECK_PORT:
        default: 10250
        description: a tcp port the ELB will check every so often - this defines health and ASG termination
        type: number
        required: true
        overrides:
          - CLUSTER_TCP_HEALTH_CHECK_PORT
    KUBE_NODE_INSTANCE_TRAFFIC_PORTS:
        default:
            - 1..65535
        description: ports to allow traffic on directly to the instances
        type: Array
        required: true
        overrides:
          - CLUSTER_INSTANCE_TRAFFIC_PORTS
    KUBE_NODE_INSTANCE_TRAFFIC_CIDRS:
        default:
            - 10.0.0.0/8
        description: cidrs that are allowed to access the instances directly
        type: Array
        required: true
        overrides:
          - CLUSTER_INSTANCE_TRAFFIC_CIDRS
    KUBE_NODE_SIZE:
        default: t2.small
        description: the image size to launch
        required: true
        overrides:
          - CLUSTER_SIZE
    KUBE_NODE_GROUP_SIZE_MIN:
        default: 3
        description: the minimum number of instances to launch
        type: number
        required: true
        overrides:
          - CLUSTER_GROUP_SIZE_MIN
    KUBE_NODE_GROUP_SIZE_MAX:
        default: 6
        description: the maxmium number of instances to launch
        type: number
        required: true
        overrides:
          - CLUSTER_GROUP_SIZE_MAX
    KUBE_NODE_HEALTH_CHECK_GRACE_PERIOD:
        default: 600
        description: the time in seconds to allow for instance to boot before checking health
        type: number
        required: true
        overrides:
          - CLUSTER_HEALTH_CHECK_GRACE_PERIOD
    KUBE_NODE_UPGRADE_COOLDOWN:
        default: 300
        description: the time in seconds between rolling instances during an upgrade
        type: number
        required: true
        overrides:
          - CLUSTER_UPGRADE_COOLDOWN
    TIMEZONE:
        default: America/LosAngeles
        description: the timezone the servers should come up in
        required: true
    KUBE_NODE_ELB_LISTENERS:
        default: >
                 [
                   {
                       :elb_protocol => 'tcp',
                       :elb_port => 10250,
                       :to_protocol => 'tcp',
                       :to_port => 10250
                   }
                 ]
        description: ports to pass through the elb to the kubernetes node cluster instances
        required: false
        overrides:
          - ELB_LISTENERS
    KUBE_NODE_KEY:
        description: the ssh key to associate with the instance(s) - blank will disable ssh
        type: string
        required: true
        default: cloudops
        overrides:
          - CLUSTER_KEY
